#!/usr/bin/env python

# This is a standalone example since at least one of the tests spans
# plinit so must be done in the same module.

# However, provide this wrapper for the standalone module so that it
# can be run just like the other python examples that are not standalone.
import x31

