#!/bin/sh
#
# File: pltar2
# Usage: pltar2
# 
# Builds tar archive of plplot files for distribution.
# No binary files should be included.
# This version creates 2 files, to make transmission easier.

# Build archive from parent directory.  It must also be unpacked from there.

cd ..

# top level text files & scripts

tar cf pl1.tar plplot/README
tar rf pl1.tar plplot/README.1st
tar rf pl1.tar plplot/COPYRIGHTS
tar rf pl1.tar plplot/Installation
tar rf pl1.tar plplot/Changes
tar rf pl1.tar plplot/pltar*
tar rf pl1.tar plplot/plzoo*
tar rf pl1.tar plplot/plzip*

# Make sure tar creates these subdirectories to make installation easier.

tar rf pl1.tar plplot/tmp/.dummy
tar rf pl1.tar plplot/lib/.dummy

# Source code & docs.

tar rf pl1.tar plplot/doc 
tar rf pl1.tar plplot/drivers
tar rf pl1.tar plplot/examples
tar rf pl1.tar plplot/fonts
tar rf pl1.tar plplot/include
tar rf pl1.tar plplot/new
tar rf pl1.tar plplot/utils

# Second tape.

tar cf pl2.tar plplot/src
tar rf pl2.tar plplot/sys
