#!/bin/sh
# pltgz
# Geoffrey Furnish
# 24 May 1994
# 
# Replacement for the infuriating, braindead tarup, which is
# constantly out of sync. grrrrrrrrrrrrrrrrr.
###############################################################################

pldir="`basename $PWD`"
tarfile=${pldir}.tar
cd ..

tar cvf $tarfile \
	`find $pldir \
	! -path \*CVS\* \
	! -path plplot/tmp\* \
	! -path \*repository\* \
	! -path \*.depend \
	! -path \*~ \
	! -path \*.o \
	! -path \*.a \
	! -path \*.sl \
	! -path \*.dat \
        -type f`

gzip ${tarfile}

echo "The resulting file is:"
ls -l ${tarfile}.gz
echo "You may now transfer ${tarfile}.gz to the remote site."
