#!/bin/sh
#
# File: plzip
# Usage: plzip
# 
# Builds zip archive of plplot files for distribution.
# No binary or CVS files should be included.

# Build archive from parent directory.  It must also be unpacked from there.

pldir="`basename $PWD`"
zipfile=${pldir}
cd ..

# Store files, leaving out contents of certain directories as well as all
# CVS-related junk.

zip ${zipfile} plplot/lib/*.fnt plplot/tmp/.dummy plplot/private/.dummy
zip -ru ${zipfile} plplot/* -x plplot/tmp plplot/lib plplot/private "*/CVS/*" "*~"
