#!/bin/sh
#
# File: plzoo2
# Usage: plzoo2
# 
# Builds zoo archive of plplot files for distribution.
# No binary files should be included.
# This version creates 2 files, to make transmission easier.

# Build archive from parent directory.  It must also be unpacked from there.

cd ..

# top level text files & scripts

zoo a pl1 plplot/README
zoo a pl1 plplot/README.1st
zoo a pl1 plplot/COPYRIGHTS
zoo a pl1 plplot/Installation
zoo a pl1 plplot/Changes
zoo a pl1 plplot/pltar*
zoo a pl1 plplot/plzoo*
zoo a pl1 plplot/plzip*

# Make sure zoo creates these subdirectories to make installation easier.

zoo a pl1 plplot/tmp/.dummy
zoo a pl1 plplot/lib/.dummy

# Source code & docs.

find plplot/doc      -print | zoo aI pl1
find plplot/drivers  -print | zoo aI pl1
find plplot/examples -print | zoo aI pl1
find plplot/fonts    -print | zoo aI pl1
find plplot/include  -print | zoo aI pl1
find plplot/new      -print | zoo aI pl1
find plplot/utils    -print | zoo aI pl1

# Second archive.

find plplot/src      -print | zoo aI pl2
find plplot/sys      -print | zoo aI pl2
