#!/bin/sh
#
# File: tarup
# Usage: tarup
# 
# Builds tar archive of plplot files for distribution.
# No binary or CVS files should be included.

# Build archive from parent directory.  It must also be unpacked from there.

pldir="`basename $PWD`"
tarfile=${pldir}.tar
cd ..

# Store files, leaving out contents of certain directories as well as all
# CVS-related junk.

echo "Creating ../${tarfile}..."
tar cf $tarfile \
	`find $pldir \
	! -path ${pldir}/tmp*/\* \
	! -path ${pldir}/private/\* \
	! -path ${pldir}/new/\* \
	! -path ${pldir}/old/\* \
	! -path \*CVS\* \
	! -path \*~ \
	! -path ${pldir}/PROBLEMS \
        -type f`

tar rf $tarfile ${pldir}/tmp/.dummy

echo "Compressing..."
gzip ${tarfile}

echo "The resulting file is:"
cd $pldir
ls -l ../${tarfile}.gz
