#!/bin/sh
#
# File: zipup
# Usage: zipup
# 
# Builds zip archive of plplot files for distribution.
# No binary or CVS files should be included.

# Build archive from parent directory.  It must also be unpacked from there.

pldir="`basename $PWD`"
zipfile=${pldir}
cd ..

# Store files, leaving out contents of certain directories as well as all
# CVS-related junk.

zip ${zipfile} ${pldir}/tmp/.dummy ${pldir}/private/.dummy

zip -ru ${zipfile} ${pldir}/* -x ${pldir}/tmp ${pldir}/private \
	${pldir}/new  ${pldir}/old "*/CVS/*" "*~"
