#!/bin/sh
#
# File: zooup
# Usage: zooup
# 
# Builds zoo archive of plplot files for distribution.
# No binary or CVS files should be included.

# Build archive from parent directory.  It must also be unpacked from there.

pldir="`basename $PWD`"
zoofile=${pldir}
cd ..

# top level text files & scripts

zoo a ${zoofile} ${pldir}/README
zoo a ${zoofile} ${pldir}/README.1st
zoo a ${zoofile} ${pldir}/COPYRIGHTS
zoo a ${zoofile} ${pldir}/Changes.log
zoo a ${zoofile} ${pldir}/ToDo
zoo a ${zoofile} ${pldir}/configure
zoo a ${zoofile} ${pldir}/tarup
zoo a ${zoofile} ${pldir}/zooup
zoo a ${zoofile} ${pldir}/zipup

# Make sure zoo creates these subdirectories to make installation easier.

zoo a ${zoofile} ${pldir}/tmp/.dummy

# Font files

zoo a ${zoofile} ${pldir}/lib/*.fnt

# Subdirectories

find ${pldir}/doc      ! -path \*CVS\* -type f | zoo aI ${zoofile}
find ${pldir}/drivers  ! -path \*CVS\* -type f | zoo aI ${zoofile}
find ${pldir}/examples ! -path \*CVS\* -type f | zoo aI ${zoofile}
find ${pldir}/fonts    ! -path \*CVS\* -type f | zoo aI ${zoofile}
find ${pldir}/include  ! -path \*CVS\* -type f | zoo aI ${zoofile}
find ${pldir}/m4       ! -path \*CVS\* -type f | zoo aI ${zoofile}
find ${pldir}/new      ! -path \*CVS\* -type f | zoo aI ${zoofile}
find ${pldir}/utils    ! -path \*CVS\* -type f | zoo aI ${zoofile}
find ${pldir}/scripts  ! -path \*CVS\* -type f | zoo aI ${zoofile}
find ${pldir}/src      ! -path \*CVS\* -type f | zoo aI ${zoofile}
find ${pldir}/sys      ! -path \*CVS\* -type f | zoo aI ${zoofile}
