#!/bin/sh
#--------------------------------*- Tcl -*------------------------------------#
# $Id: x01 11045 2010-05-31 19:46:51Z airwin $
#
# Maurice LeBrun
# 12/24/02
#
# A front-end to x00.tcl for running directly from the command line, locating
# pltcl via PATH.
# Handles all usual plplot command arguments.  See "pltcl -h" for info.
#-----------------------------------------------------------------------------#
#\
exec pltcl -f "$0" ${1+"$@"}

source x00.tcl

plgver ver
puts [format "PLplot library version: %s" $ver ]

plinit
x00
plend
