#!/bin/sh
#--------------------------------*- Tcl -*------------------------------------#
# $Id$
#
# Maurice LeBrun
# 12/24/02
#
# A front-end to x16.tcl for running directly from the command line, locating
# pltcl via PATH.
# Handles all usual plplot command arguments.  See "pltcl -h" for info.
#-----------------------------------------------------------------------------#
#\
exec pltcl -f "$0" ${1+"$@"}

source x16.tcl

# For consistency with C version these need to be set before plinit is
# called.
plspal0 "cmap0_black_on_white.pal"
plspal1 "cmap1_gray.pal" 1
plscmap0n 3

plinit
x16
plend
