#!/bin/sh
#--------------------------------*- Tcl -*------------------------------------#
# $Id$
#
# Maurice LeBrun
# 12/24/02
#
# A front-end to x18.tcl for running directly from the command line, locating
# pltcl via PATH.
# Handles all usual plplot command arguments.  See "pltcl -h" for info.
#-----------------------------------------------------------------------------#
#\
exec pltcl -f "$0" ${1+"$@"}

source x18.tcl

plinit
x18
plend
