#!/bin/sh
#--------------------------------*- Tcl -*------------------------------------#
# Arjen Markus
# 08/18/08
#
# A front-end to x26.tcl for running directly from the command line, locating
# pltcl via PATH.
# Handles all usual plplot command arguments.  See "pltcl -h" for info.
#-----------------------------------------------------------------------------#
#\
exec pltcl -f "$0" ${1+"$@"}

source x27.tcl

plinit
x27
plend
