/*
 * matrixDecls.h --
 *
 *	Declarations of functions in the platform independent public Matrix API.
 *
 * Copyright (c) 2000 by Vince Darley
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 */

#ifndef _MATRIXDECLS
#define _MATRIXDECLS

/*
 * WARNING: This file is automatically generated by the tools/genStubs.tcl
 * script.  Any modifications to the function declarations below should be made
 * in the generic/matrix.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

/*
 * Exported function declarations:
 */

/* 0 */
EXTERN tclMatrix*	Tcl_GetMatrixPtr _ANSI_ARGS_((Tcl_Interp * interp, 
				char* matName));
/* 1 */
EXTERN int		Tcl_MatrixInstallXtnsn _ANSI_ARGS_((char * cmd, 
				tclMatrixXtnsnProc proc));

typedef struct MatrixStubHooks {
    struct MatrixIntStubs *matrixIntStubs;
} MatrixStubHooks;

typedef struct MatrixStubs {
    int magic;
    struct MatrixStubHooks *hooks;

    tclMatrix* (*tcl_GetMatrixPtr) _ANSI_ARGS_((Tcl_Interp * interp, char* matName)); /* 0 */
    int (*tcl_MatrixInstallXtnsn) _ANSI_ARGS_((char * cmd, tclMatrixXtnsnProc proc)); /* 1 */
} MatrixStubs;

#ifdef __cplusplus
extern "C" {
#endif
extern MatrixStubs *matrixStubsPtr;
#ifdef __cplusplus
}
#endif

#if defined(USE_MATRIX_STUBS) && !defined(USE_MATRIX_STUB_PROCS)

/*
 * Inline function declarations:
 */

#ifndef Tcl_GetMatrixPtr
#define Tcl_GetMatrixPtr \
	(matrixStubsPtr->tcl_GetMatrixPtr) /* 0 */
#endif
#ifndef Tcl_MatrixInstallXtnsn
#define Tcl_MatrixInstallXtnsn \
	(matrixStubsPtr->tcl_MatrixInstallXtnsn) /* 1 */
#endif

#endif /* defined(USE_MATRIX_STUBS) && !defined(USE_MATRIX_STUB_PROCS) */

/* !END!: Do not edit above this line. */

#endif /* _MATRIXDECLS */

