/*
 * matrixIntDecls.h --
 *
 *	This file contains the declarations for all unsupported
 *	functions that are exported by the Matrix library.  These
 *	interfaces are not guaranteed to remain the same between
 *	versions.  Use at your own risk.
 *
 */

#ifndef _MATRIXINTDECLS
#define _MATRIXINTDECLS

/*
 * WARNING: This file is automatically generated by the tools/genStubs.tcl
 * script.  Any modifications to the function declarations below should be made
 * in the generic/tclInt.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

/*
 * Exported function declarations:
 */


typedef struct MatrixIntStubs {
    int magic;
    struct MatrixIntStubHooks *hooks;

} MatrixIntStubs;

#ifdef __cplusplus
extern "C" {
#endif
extern MatrixIntStubs *matrixIntStubsPtr;
#ifdef __cplusplus
}
#endif

#if defined(USE_MATRIX_STUBS) && !defined(USE_MATRIX_STUB_PROCS)

/*
 * Inline function declarations:
 */


#endif /* defined(USE_MATRIX_STUBS) && !defined(USE_MATRIX_STUB_PROCS) */

/* !END!: Do not edit above this line. */

#endif /* _MATRIXINTDECLS */
