/* 
 * matrixStubInit.c --
 *
 *	This file contains the initializers for the Matrix stub vectors.
 *
 */

#include "tclMatrix.h"
#include "matrixIntDecls.h"

/*
 * WARNING: The contents of this file is automatically generated by the
 * tools/genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the generic/matrix.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

MatrixIntStubs matrixIntStubs = {
    TCL_STUB_MAGIC,
    NULL,
};

static MatrixStubHooks matrixStubHooks = {
    &matrixIntStubs
};

MatrixStubs matrixStubs = {
    TCL_STUB_MAGIC,
    &matrixStubHooks,
    Tcl_GetMatrixPtr, /* 0 */
    Tcl_MatrixInstallXtnsn, /* 1 */
};

/* !END!: Do not edit above this line. */
