#!/bin/sh
#--------------------------------*- Tcl -*------------------------------------#
# Maurice LeBrun
# 12/24/02
#
# A front-end to x29.tcl for running directly from the command line, locating
# pltcl via PATH.
# Handles all usual plplot command arguments.  See "pltcl -h" for info.
#-----------------------------------------------------------------------------#
#\
exec pltcl -f "$0" ${1+"$@"}

source x29.tcl

plinit
x29
plend
