/*
 *  Source machine generated by GadToolsBox V1.4
 *  which is (c) Copyright 1991,92 Jaba Development
 */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <clib/exec_protos.h>
#include <clib/intuition_protos.h>
#include <clib/gadtools_protos.h>
#include <clib/graphics_protos.h>
#include <clib/utility_protos.h>
#include <string.h>

#include "plplotGT.h"

struct Screen         *Scr = NULL;
APTR                   VisualInfo = NULL;
struct Window         *plplotGTWnd = NULL;
struct Menu           *plplotGTMenus = NULL;
struct IntuiMessage    plplotGTMsg;
UWORD                  plplotGTLeft = 0;
UWORD                  plplotGTTop = 0;
UWORD                  plplotGTWidth = 710;
UWORD                  plplotGTHeight = 458;
UBYTE                 *plplotGTWdt = (UBYTE *)"Plplot 5.0";

struct TextAttr topaz11 = {
	( STRPTR )"topaz.font", 11, 0x00, 0x42 };

struct NewMenu plplotGTNewMenu[] = {
	NM_TITLE, (STRPTR)"Project", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Open", (STRPTR)"O", NM_ITEMDISABLED, 0L, (APTR)plplotGTItem0,
	NM_ITEM, (STRPTR)"Save", NULL, NM_ITEMDISABLED, 0L, (APTR)plplotGTItem1,
	NM_ITEM, (STRPTR)"Save As", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"ILBM (IFF)", NULL, 0, 0L, (APTR)plplotGTItem2,
	NM_ITEM, (STRPTR)"Print", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Bitmap", NULL, 0, 0L, (APTR)plplotGTItem3,
	NM_SUB, (STRPTR)"Full page (landscape)", NULL, 0, 0L, (APTR)plplotGTItem4,
	NM_SUB, (STRPTR)"Full page (portrait)", NULL, 0, 0L, (APTR)plplotGTItem5,
	NM_ITEM, (STRPTR)"About...", NULL, NM_ITEMDISABLED, 0L, (APTR)plplotGTItem6,
	NM_ITEM, (STRPTR)"Quit", (STRPTR)"Q", 0, 0L, (APTR)plplotGTItem7,
	NM_TITLE, (STRPTR)"Settings", NULL, 0, NULL, NULL,
	NM_ITEM, (STRPTR)"Reset", NULL, 0, 0L, (APTR)plplotGTItem8,
	NM_ITEM, (STRPTR)"Screen Type", NULL, 0, NULL, NULL,
	NM_SUB, (STRPTR)"Workbench", NULL, 0, 0L, (APTR)plplotGTItem9,
	NM_SUB, (STRPTR)"Custom", NULL, 0, 0L, (APTR)plplotGTItem10,
	NM_ITEM, (STRPTR)"Screen parameters", NULL, 0, 0L, (APTR)plplotGTItem11,
	NM_END, NULL, NULL, 0, 0L, NULL };

struct ColorSpec ScreenColors[] = {
	 0, 0x09, 0x09, 0x08,
	 1, 0x00, 0x00, 0x00,
	 2, 0x0C, 0x0C, 0x0C,
	 3, 0x05, 0x06, 0x0B,
	~0, 0x00, 0x00, 0x00 };

UWORD DriPens[] = {
	0,1,1,2,1,3,1,0,2,~0 };

int SetupScreen( void )
{
	if ( ! ( Scr = OpenScreenTags( NULL, SA_Left,	0,
					SA_Top,		0,
					SA_Width,	710,
					SA_Height,	472,
					SA_Depth,	2,
					SA_Colors,	&ScreenColors[0],
					SA_Font,	&topaz11,
					SA_Type,	CUSTOMSCREEN,
					SA_DisplayID,	NTSC_MONITOR_ID|HIRESLACE_KEY,
					SA_Pens,	&DriPens[0],
					SA_Title,	"PLPLOT.1",
					TAG_DONE )))
		return( 1L );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		CloseScreen( Scr );
		Scr = NULL;
	}
}

int HandleplplotGTIDCMP( void )
{
	struct IntuiMessage	*m;
	struct MenuItem		*n;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( plplotGTWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&plplotGTMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( plplotGTMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( plplotGTWnd );
				GT_EndRefresh( plplotGTWnd, TRUE );
				break;

			case	IDCMP_VANILLAKEY:
				running = plplotGTVanillaKey();
				break;

				break;

			case	IDCMP_MENUPICK:
				while( plplotGTMsg.Code != MENUNULL ) {
					n = ItemAddress( plplotGTMenus, plplotGTMsg.Code );
					func = (void *)(GTMENUITEM_USERDATA( n ));
					running = func();
					plplotGTMsg.Code = n->NextSelect;
				}
				break;
		}
	}
	return( running );
}

int OpenplplotGTWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		offx = 0, offy = Scr->WBorTop + Scr->RastPort.TxHeight + 1;

	if ( ! ( plplotGTMenus = CreateMenus( plplotGTNewMenu, GTMN_FrontPen, 0L, TAG_DONE )))
		return( 3L );

	LayoutMenus( plplotGTMenus, VisualInfo, GTMN_TextAttr, &topaz11, TAG_DONE );

	if ( ! ( plplotGTWnd = OpenWindowTags( NULL,
				WA_Left,	plplotGTLeft,
				WA_Top,		plplotGTTop,
				WA_Width,	plplotGTWidth,
				WA_Height,	plplotGTHeight + offy,
				WA_IDCMP,	IDCMP_MENUPICK|IDCMP_VANILLAKEY|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_SMART_REFRESH|WFLG_BACKDROP|WFLG_BORDERLESS|WFLG_ACTIVATE,
				WA_ScreenTitle,	"Plplot 5.0",
				WA_CustomScreen,	Scr,
				TAG_DONE )))
	return( 4L );

	SetMenuStrip( plplotGTWnd, plplotGTMenus );
	GT_RefreshWindow( plplotGTWnd, NULL );

	return( 0L );
}

void CloseplplotGTWindow( void )
{
	if ( plplotGTMenus      ) {
		ClearMenuStrip( plplotGTWnd );
		FreeMenus( plplotGTMenus );
		plplotGTMenus = NULL;	}

	if ( plplotGTWnd        ) {
		CloseWindow( plplotGTWnd );
		plplotGTWnd = NULL;
	}
}
