/*
 *  Source machine generated by GadToolsBox V1.4
 *  which is (c) Copyright 1991,92 Jaba Development
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )


extern struct Screen        *Scr;
extern APTR                  VisualInfo;
extern struct Window        *plplotGTWnd;
extern struct Menu          *plplotGTMenus;
extern struct IntuiMessage   plplotGTMsg;
extern UWORD                 plplotGTLeft;
extern UWORD                 plplotGTTop;
extern UWORD                 plplotGTWidth;
extern UWORD                 plplotGTHeight;
extern UBYTE                *plplotGTWdt;
extern struct TextAttr       topaz11;
extern struct NewMenu        plplotGTNewMenu[];
extern struct ColorSpec      ScreenColors[];
extern UWORD                 DriPens[];

extern int plplotGTItem0( void );
extern int plplotGTItem1( void );
extern int plplotGTItem2( void );
extern int plplotGTItem3( void );
extern int plplotGTItem4( void );
extern int plplotGTItem5( void );
extern int plplotGTItem6( void );
extern int plplotGTItem7( void );
extern int plplotGTItem8( void );
extern int plplotGTItem9( void );
extern int plplotGTItem10( void );
extern int plplotGTItem11( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleplplotGTIDCMP( void );
extern int plplotGTVanillaKey();
extern int OpenplplotGTWindow( void );
extern void CloseplplotGTWindow( void );
