.\" -*- nroff -*-
.TH PLTCL 1
.SH NAME
pltcl \- Tcl interface to PLplot
.SH SYNOPSIS
.B pltcl
.SH "DESCRIPTION"
This manual page documents briefly the
.BR pltcl
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.B plrender
is the main program for Tcl nterface to PLplot.  Allows interpretive
execution of plotting primitives without regard to output driver.
.SH "SEE ALSO"
See /usr/share/doc/plplot/plplot.ps.gz for more details.
.SH AUTHOR
This manual page was written by Rafael Laboissiere <rafael@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
