#!/bin/sh
#
# postinst script for the Debian GNU/Linux plplot package
#
# Written by Rafael Laboissiere <rafael@icp.inpg.fr>
# on Fri Nov 13 02:54:30 CET 1998

set -e

case "$1" in
    remove|purge)
        install-info --quiet --remove plplot
    ;;

    upgrade)
    ;;

    failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac                 

