#!/bin/sh
#--------------------------------*- Tcl -*------------------------------------#
# $Id$
# Maurice LeBrun
# Dec 21 2000
#-----------------------------------------------------------------------------#
# @> Tcl script to create a TclIndex file.  Imports Itcl so it will pick up
# @> incr tcl class definitions, but only if they are fully qualified (i.e.
# @> itcl::class), due to a bug in the incr tcl autoloading extension.
#-----------------------------------------------------------------------------#
#\
exec tclsh "$0" ${1+"$@"}

if {[catch {package require Itcl}]} {

# Error including Itcl -- only include tcl files
    auto_mkindex . *.tcl

} else {

# Package require succeeded -- include all itcl, itk files.
# Think there are enough naming conventions?
    auto_mkindex . *.tcl *.itcl *.itk *.ith *.itm
}

exit
