cmake_policy(SET CMP0007 NEW)
file(STRINGS ${FILENAME} lines)
list(LENGTH lines nlines)
# There are currently groups of 9 lines for each
# gtk software package specifying the required
# build-configuration information.
set(group_size 9)
set(remove_indices 0 1 2 3 4 5 6 7 8)
math(EXPR max_index "(${nlines}/${group_size}) - 1")
foreach(index RANGE 0 ${max_index})
  list(GET lines 0 package)
  message("${package}")
  list(GET lines 1 config_type)
  message("${config_type}")
  list(GET lines 2 config_arguments)
  message("${config_arguments}")
  list(GET lines 3 download_hash_type)
  message("${download_hash_type}")
  list(GET lines 4 download_hash)
  message("${download_hash}")
  list(GET lines 5 download_href)
  message("${download_href}")
  list(GET lines 6 dependencies)
  message("${dependencies}")
  list(GET lines 7 suggests)
  message("${suggests}")
  list(GET lines 8 after)
  message("${after}")
  list(REMOVE_AT lines ${remove_indices})
endforeach(index RANGE 0 ${max_index})
