option(ENABLE_ada "Build Ada interface to PLplot" OFF)
# Eventually configure this.
set(GNATMAKE_EXECUTABLE gnatmake)
# This location can be obtained from last element in object search path
# generated by "gnatls -v" command.
# This works for Debian stable.  Eventually configure this.
set(GNAT_DIR /usr/lib/gcc-lib/i486-linux/3.3.5/adalib/)
