find_package(Qt4)
if(PLD_rasterqt OR PLD_epsqt OR PLD_pdfqt OR PLD_qtwidget OR PLD_svgqt)
  if(PLD_svgqt AND ${QT_VERSION_MINOR} GREATER 2)
    set(QT_USE_QTSVG 1)
  endif(PLD_svgqt AND ${QT_VERSION_MINOR} GREATER 2)
  include(${QT_USE_FILE})
  if(NOT QT4_FOUND)
    set(PLD_rasterqt OFF CACHE BOOL "Enable Qt raster device" FORCE)
    set(PLD_epsqt OFF CACHE BOOL "Enable Qt EPS device" FORCE)
    set(PLD_pdfqt OFF CACHE BOOL "Enable Qt PDF device" FORCE)
    set(PLD_qtwidget OFF CACHE BOOL "Enable Qt interactive device" FORCE)
    set(PLD_svgqt OFF CACHE BOOL "Enable Qt SVG device" FORCE)
  else(NOT QT4_FOUND)
    set(qt_COMPILE_FLAGS)
    foreach(DIR ${QT_INCLUDES})
      set(qt_COMPILE_FLAGS "${qt_COMPILE_FLAGS} -I${DIR}")
    endforeach(DIR ${QT_INCLUDES})
    
    set(qt_LINK_FLAGS ${QT_LIBRARIES})
    set(DRIVERS_LINK_FLAGS ${DRIVERS_LINK_FLAGS} ${qt_LINK_FLAGS})
  endif(NOT QT4_FOUND)
endif(PLD_rasterqt OR PLD_epsqt OR PLD_pdfqt OR PLD_qtwidget OR PLD_svgqt)
