# Naive way to (try to?) dissociate the SVG driver (not available on Qt 4.2) from the other drivers. Yet to be tested!

if(PLD_svgqt)
	FIND_PACKAGE(Qt4)
	SET(QT_USE_QTSVG 1)
	INCLUDE(${QT_USE_FILE})
	if(NOT QT4_FOUND)
		set(PLD_svgqt OFF CACHE BOOL "Enable Qt SVG device" FORCE)
	else(NOT QT4_FOUND)
		set(qt_COMPILE_FLAGS)
 		foreach(DIR ${QT_INCLUDES})
			set(qt_COMPILE_FLAGS "${qt_COMPILE_FLAGS} -I${DIR}")
		endforeach(DIR ${QT_INCLUDES})
		
		set(qt_LINK_FLAGS ${QT_LIBRARIES})
		set(DRIVERS_LINK_FLAGS ${DRIVERS_LINK_FLAGS} ${qt_LINK_FLAGS})
	endif(NOT QT4_FOUND)
endif(PLD_svgqt)

if(PLD_rasterqt OR PLD_epspdfqt OR PLD_qtwidget)
	FIND_PACKAGE(Qt4)
	INCLUDE(${QT_USE_FILE})
	if(NOT QT4_FOUND)
		set(PLD_rasterqt OFF CACHE BOOL "Enable Qt raster device" FORCE)
		set(PLD_epspdfqt OFF CACHE BOOL "Enable Qt EPS/PDF device" FORCE)
		set(PLD_qtwidget OFF CACHE BOOL "Enable Qt EPS/PDF device" FORCE)
	else(NOT QT4_FOUND)
		set(qt_COMPILE_FLAGS)
 		foreach(DIR ${QT_INCLUDES})
			set(qt_COMPILE_FLAGS "${qt_COMPILE_FLAGS} -I${DIR}")
		endforeach(DIR ${QT_INCLUDES})
		
		set(qt_LINK_FLAGS ${QT_LIBRARIES})
		set(DRIVERS_LINK_FLAGS ${DRIVERS_LINK_FLAGS} ${qt_LINK_FLAGS})
	endif(NOT QT4_FOUND)
endif(PLD_rasterqt OR PLD_epspdfqt OR PLD_qtwidget)